### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by VoipSip** [behnambm/spotify-status#1]
hello sir thank you for the good script but i want more help for other script cracker login page for something like that 

i want great script for cracking login page for this type with multi threading and multiprocessing

thank you

**Comment by behnambm** [comment]
:))))))))
REALLY ????

**Comment by behnambm** [comment]
I have to edit your comment.
because you are revealing sensitive content.

**Comment by behnambm** [comment]
I answered you here : [link](https://github.com/behnambm/nordvpn-checker/issues/3)
